"""``zeroer_features`` reproduces py_entitymatching's feature matrix exactly.

``zeroer_features`` is a reimplementation, not a port — there is no upstream
code to diff it against, only output to compare. These tests pin that output
against genuine Magellan matrices generated by upstream's own extraction path
(``tests/generate_magellan_fixtures.py``, run under the py3.6 ZeroER env) on a
seeded 2% sample of each dataset's blocked candidate set.

Both sides are fed the same tables, so a failure here is a feature-code
difference and nothing else. Assertions are exact-by-intent: identical column
names in identical order, and values equal to ~1 ULP.

Run:  pytest tests/test_feature_parity.py -v
"""
import numpy as np
import pandas as pd
import pytest

from generate_magellan_fixtures import DATASETS, FIXTURES, _tables
from data import BENCH_DIR
from zeroer_features import build_zeroer_features

# Magellan and this port both compute in float64 over the same inputs; the only
# expected difference is operation-order rounding, i.e. a few ULP.
TOLERANCE = 1e-12

FIXTURE_MISSING = (
    "no fixture for {}: run "
    "`~/miniconda3/envs/ZeroER/bin/python tests/generate_magellan_fixtures.py {}`")


def _reference(dataset):
    path = f"{FIXTURES}/{dataset}.csv.gz"
    try:
        return pd.read_csv(path, dtype={"ltable_id": str, "rtable_id": str})
    except FileNotFoundError:
        pytest.skip(FIXTURE_MISSING.format(dataset, dataset))


@pytest.mark.parametrize("dataset", sorted(DATASETS))
def test_matches_py_entitymatching(dataset):
    reference = _reference(dataset)
    left, right = _tables(dataset, BENCH_DIR)

    # positional pairs into the concatenated table, the form the port takes
    row_of_left = {str(v): i for i, v in enumerate(left["id"])}
    row_of_right = {str(v): i for i, v in enumerate(right["id"])}
    limit = len(left)
    pairs = [(row_of_left[a], limit + row_of_right[b])
             for a, b in zip(reference["ltable_id"], reference["rtable_id"])]

    attributes = [c for c in left.columns if c in right.columns]
    # n_jobs=-1 keeps the long-description datasets to a sane runtime, and
    # doubles as a check on build_zeroer_features' claim that the parallel
    # result is identical to the serial one — it only forks above 2000 pairs,
    # so the smaller datasets here still exercise the serial path.
    ours = build_zeroer_features(
        pairs, pd.concat([left, right], ignore_index=True), attributes,
        dataset_limit=limit, drop_zero_variance=False, n_jobs=-1)

    # The constant-column drop is subset-dependent, so it is disabled above and
    # the comparison is over the full name-filtered set both sides produce.
    expected = reference.drop(columns=["ltable_id", "rtable_id"])
    assert list(ours.columns) == list(expected.columns)

    difference = np.abs(ours.to_numpy(float) - expected.to_numpy(float))
    assert difference.max() <= TOLERANCE, (
        f"{dataset}: max |difference| {difference.max():.3e} in column "
        f"{expected.columns[difference.max(axis=0).argmax()]}")
