"""
Exact reconstruction of ZeroER's *pre-matching* similarity feature matrix.

Reproduces, value for value, the upstream path (chu-data-lab/zeroer):

    em.read_csv_metadata          (pandas dtype inference, per table)
    em.get_attr_types             (per-table attribute typing)
    extract_features              (type-upgrade rule + name-based feature filter)
      get_features                (magellan_modified_feature_generation lookup)
      em.extract_feature_vecs     (Magellan sim/tok functions applied per pair)
      .fillna(0)
    gather_similarity_features    (drop distance/non-normalised + constant cols)

without depending on py_entitymatching. Sim/tok primitives come from
py_stringmatching — exactly what Magellan wraps — and every wrapper detail is
ported from py_entitymatching 0.4.0: NaN in either value -> NaN feature
(-> 0 after fillna), str() coercion of non-strings, *bag* q-gram/delimiter
tokenisation (padded q-grams), raw-value exact_match, abs_norm's both-zero -> 0
and <=1e-4 snap, and Magellan's `{attr}_{attr}_{sim}_{tok}_{tok}` names.

pyJedAI note: ``Data`` stringifies tables (astype(str)), while upstream ZeroER
works on read_csv-typed frames (year/price numeric, missing = NaN). To match,
columns are first passed through ``_as_read_csv``, which undoes stringification
('nan'/'' -> NaN, fully-numeric-parseable column -> numeric) — a no-op on
frames that already carry read_csv dtypes.

Verified column-for-column and value-for-value (max diff 1 ULP) against
feature matrices generated by the upstream code on fodors_zagats, dblp_acm,
abt_buy (two-table) and fodors_zagats_single (single-table dedup), on both
raw-dtype and astype(str) inputs.

Caveat: upstream's abt_buy *blocking function* concatenates Buy's description
with its manufacturer before extraction — that is dataset prep, not feature
generation, so end-to-end parity on abt_buy needs the same concat upstream of
this module.
"""
from __future__ import annotations

import numpy as np
import pandas as pd
import py_stringmatching as sm

# ---------------------------------------------------------------------------
# Magellan machinery constants
# ---------------------------------------------------------------------------

# extract_features' rank for the cross-table type-upgrade rule.
_TYPE_RANK = {'boolean': 1, 'numeric': 2, 'str_eq_1w': 3, 'str_bt_1w_5w': 4,
              'str_bt_5w_10w': 5, 'str_gt_10w': 6, 'un_determined': 7}

# Magellan's full per-type feature lookup (_get_feat_lkp_tbl), in order.
# (sim_function, tokenizer); tokenizer None = whole-string function.
_STR_LONG = [('cosine', 'dlm_dc0'), ('cosine', 'qgm_3'),
             ('dice', 'dlm_dc0'), ('dice', 'qgm_3'),
             ('monge_elkan', 'dlm_dc0'), ('monge_elkan', 'qgm_3'),
             ('overlap_coeff', 'dlm_dc0'), ('overlap_coeff', 'qgm_3'),
             ('jaccard', 'dlm_dc0'), ('jaccard', 'qgm_3')]
_FEAT_LKP = {
    'str_eq_1w': [('affine', None),
                  ('cosine', 'qgm_2'), ('cosine', 'qgm_3'),
                  ('dice', 'qgm_2'), ('dice', 'qgm_3'),
                  ('lev_dist', None), ('lev_sim', None), ('jaro', None),
                  ('jaro_winkler', None), ('exact_match', None),
                  ('smith_waterman', None), ('needleman_wunsch', None),
                  ('monge_elkan', 'qgm_2'), ('monge_elkan', 'qgm_3'),
                  ('overlap_coeff', 'qgm_2'), ('overlap_coeff', 'qgm_3'),
                  ('jaccard', 'qgm_2'), ('jaccard', 'qgm_3')],
    'str_bt_1w_5w': [('affine', None),
                     ('cosine', 'dlm_dc0'), ('cosine', 'qgm_3'),
                     ('dice', 'dlm_dc0'), ('dice', 'qgm_3'),
                     ('lev_dist', None), ('lev_sim', None), ('jaro', None),
                     ('jaro_winkler', None), ('exact_match', None),
                     ('smith_waterman', None), ('needleman_wunsch', None),
                     ('monge_elkan', 'dlm_dc0'), ('monge_elkan', 'qgm_3'),
                     ('overlap_coeff', 'dlm_dc0'), ('overlap_coeff', 'qgm_3'),
                     ('jaccard', 'dlm_dc0'), ('jaccard', 'qgm_3')],
    'str_bt_5w_10w': _STR_LONG,
    'str_gt_10w': _STR_LONG,
    'numeric': [('exact_match', None), ('abs_norm', None), ('lev_dist', None),
                ('lev_sim', None), ('rel_diff', None)],
    'boolean': [('exact_match', None)],
    'un_determined': [],
}

# get_fn_name's short names; anything absent passes through unchanged
# (dice, overlap_coeff, affine, lev_dist, lev_sim).
_SHORT = {'jaccard': 'jac', 'cosine': 'cos', 'monge_elkan': 'mel',
          'needleman_wunsch': 'nmw', 'smith_waterman': 'sw', 'jaro': 'jar',
          'jaro_winkler': 'jwn', 'exact_match': 'exm', 'abs_norm': 'anm',
          'rel_diff': 'rdf'}

# extract_features + gather_similarity_features drop every feature whose
# *name* contains one of these (distance + non-normalised functions).
_DROP_SUBSTRINGS = ('lev_dist', 'rdf', 'aff', 'sw', 'swn', 'nmw')

# Magellan tokenizer defaults: padded q-grams, bag (not set) semantics.
_TOKENIZERS = {
    'qgm_2': sm.QgramTokenizer(qval=2),
    'qgm_3': sm.QgramTokenizer(qval=3),
    'dlm_dc0': sm.DelimiterTokenizer(delim_set=[' ']),
}
_TOKEN_MEASURES = {'cosine': sm.Cosine(), 'dice': sm.Dice(),
                   'jaccard': sm.Jaccard(),
                   'overlap_coeff': sm.OverlapCoefficient(),
                   'monge_elkan': sm.MongeElkan()}
_LEV = sm.Levenshtein()
_JARO = sm.Jaro()
_JW = sm.JaroWinkler()


# ---------------------------------------------------------------------------
# read_csv dtype reconstruction + Magellan type inference
# ---------------------------------------------------------------------------

def _as_read_csv(column: pd.Series) -> pd.Series:
    """Reproduce pandas.read_csv dtype inference on a possibly astype(str)-
    stringified column. No-op for columns already carrying read_csv dtypes."""
    if (pd.api.types.is_numeric_dtype(column)
            or pd.api.types.is_bool_dtype(column)):
        return column
    col = column.mask(column.isin(['nan', '']))  # astype(str) artifacts -> NaN
    non_null = col.dropna()
    if non_null.empty or not non_null.map(lambda v: isinstance(v, str)).all():
        return col
    numeric = pd.to_numeric(col, errors='coerce')
    if numeric.notna().equals(col.notna()):
        return numeric  # int64 when complete + integral, float64 otherwise
    if non_null.isin(['True', 'False']).all():
        return col.map({'True': True, 'False': False})
    return col


def infer_attr_type(column: pd.Series) -> str:
    """Exact port of em.get_attr_types._get_type (run _as_read_csv first)."""
    column = column.dropna()
    type_list = list(set(column.map(type).tolist()))
    if len(type_list) == 0:
        return 'un_determined'
    if len(type_list) > 1:
        raise AssertionError(
            'Column %s qualifies to be more than one type.' % column.name)
    returned_type = type_list[0]
    if returned_type == bool or returned_type == np.bool_:
        return 'boolean'
    elif returned_type == str:
        average_token_len = pd.Series.mean(
            column.str.split().apply(
                lambda x: len(x) if isinstance(x, list) else np.nan))
        if average_token_len == 1:
            return 'str_eq_1w'
        elif average_token_len <= 5:
            return 'str_bt_1w_5w'
        elif average_token_len <= 10:
            return 'str_bt_5w_10w'
        else:
            return 'str_gt_10w'
    else:
        return 'numeric'


# ---------------------------------------------------------------------------
# Magellan sim-function ports (NaN in either value -> NaN, fillna(0) later)
# ---------------------------------------------------------------------------

def _abs_norm(d1, d2):
    try:
        d1, d2 = float(d1), float(d2)
    except ValueError:
        return np.nan
    if d1 == 0.0 and d2 == 0.0:
        return 0
    x = abs(d1 - d2) / max(abs(d1), abs(d2))
    if x <= 10e-5:  # Magellan's snap-to-equal threshold
        x = 0
    return 1.0 - x


def _to_str(v):
    return v if isinstance(v, str) else str(v)  # gh.convert_to_str_unicode


def _compute(sim, tok_key, raw_l, raw_r, null, strs_l, strs_r, toks):
    n = len(raw_l)
    out = np.full(n, np.nan)
    if tok_key is not None:
        measure = _TOKEN_MEASURES[sim]
        toks_l, toks_r = toks[tok_key]
        for i in range(n):
            if not null[i]:
                out[i] = measure.get_raw_score(toks_l[i], toks_r[i])
        return out
    for i in range(n):
        if null[i]:
            continue
        if sim == 'exact_match':
            out[i] = 1 if raw_l[i] == raw_r[i] else 0
        elif sim == 'abs_norm':
            out[i] = _abs_norm(raw_l[i], raw_r[i])
        elif sim == 'lev_sim':
            out[i] = _LEV.get_sim_score(strs_l[i], strs_r[i])
        elif sim == 'jaro':
            out[i] = _JARO.get_raw_score(strs_l[i], strs_r[i])
        elif sim == 'jaro_winkler':
            out[i] = _JW.get_raw_score(strs_l[i], strs_r[i])
        else:  # affine/sw/nmw/lev_dist/rel_diff never survive the name filter
            raise ValueError(sim)
    return out


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_zeroer_features(pairs, entities: pd.DataFrame, attributes,
                          dataset_limit: int | None = None,
                          drop_zero_variance: bool = True) -> pd.DataFrame:
    """
    pairs: list of (left_row, right_row) positional indices into `entities`
        (pyJedAI candidate pairs: right-table rows offset by dataset_limit).
    entities: the record table — for clean-clean ER the concat of both tables
        (pyJedAI's data.entities), for dedup a single table.
    attributes: attribute names to featurize, in left-table column order
        (upstream featurizes every shared attribute; 'id' is skipped).
    dataset_limit: first row of the right table (pyJedAI's data.dataset_limit);
        None = single-table dedup. Needed because upstream types each table
        separately, then upgrades mismatched types to the higher rank.
    """
    if not pairs:
        return pd.DataFrame()
    li, ri = map(np.asarray, zip(*pairs))
    blocks = []
    for attr in attributes:
        if attr == 'id':  # upstream drops id-based features
            continue
        col = _as_read_csv(entities[attr])
        if dataset_limit is None:
            attr_type = infer_attr_type(col)
        else:
            type_l = infer_attr_type(col.iloc[:dataset_limit])
            type_r = infer_attr_type(col.iloc[dataset_limit:])
            attr_type = max(type_l, type_r, key=_TYPE_RANK.get)

        attr_tag = '_'.join(attr.split())
        feats = []  # (column_name, sim, tok_key) surviving the name filter
        for sim, tok_key in _FEAT_LKP[attr_type]:
            name = '_'.join([attr_tag, attr_tag, _SHORT.get(sim, sim)]
                            + ([tok_key, tok_key] if tok_key else []))
            if not any(f in name for f in _DROP_SUBSTRINGS):
                feats.append((name, sim, tok_key))
        if not feats:
            continue

        raw = col.to_numpy()
        raw_l, raw_r = raw[li], raw[ri]
        null = pd.isnull(raw_l) | pd.isnull(raw_r)
        strs = np.array([_to_str(v) for v in raw], dtype=object)
        strs_l, strs_r = strs[li], strs[ri]

        # Tokenize once per unique string value, per needed tokenizer.
        needed = {t for _, _, t in feats if t is not None}
        uniq, inv = np.unique(strs, return_inverse=True)
        toks = {}
        for tok_key in needed:
            tokenize = _TOKENIZERS[tok_key].tokenize
            tok_u = [tokenize(u) for u in uniq]
            toks[tok_key] = ([tok_u[i] for i in inv[li]],
                             [tok_u[i] for i in inv[ri]])

        data = {name: _compute(sim, tok_key, raw_l, raw_r, null,
                               strs_l, strs_r, toks)
                for name, sim, tok_key in feats}
        blocks.append(pd.DataFrame(data))

    if not blocks:
        return pd.DataFrame()
    fm = pd.concat(blocks, axis=1)
    fm.fillna(value=0, inplace=True)
    if drop_zero_variance:
        fm = fm.loc[:, fm.nunique() > 1]
    return fm


if __name__ == '__main__':
    entities = pd.DataFrame({
        'id':    [0, 1, 2, 3, 4, 5],
        'name':  ['Sony Vaio Laptop', 'Sony Viao Laptop', 'Dell XPS 13',
                  'Apple MacBook Pro 16 inch retina display model',
                  'apple macbook pro 16 inch retina display model',
                  'Dell XPS 13'],
        'brand': ['Sony', 'Sony', 'Dell', 'Apple', 'Apple', 'Dell'],
        'price': ['999', '999', '1200', '1999', 'nan', '1200'],
    })
    pairs = [(0, 1), (0, 2), (2, 5), (3, 4), (1, 1)]
    attrs = ['name', 'brand', 'price']

    for a in attrs:
        print(f'{a:6s} -> inferred type: '
              f'{infer_attr_type(_as_read_csv(entities[a]))}')
    print()

    fm = build_zeroer_features(pairs, entities, attrs)
    pd.set_option('display.width', 240, 'display.max_columns', 60)
    print('shape:', fm.shape)
    print(fm.round(3).T)
